import type { FastifyReply, FastifyRequest } from "fastify";
import { fail, ok } from "../../models/schemas.js";
import { parseWorkflowYAMLStrict } from "../../parser/workflow.js";
import type { RouteDefinition } from "../generated-routes.js";
import { bodyRecord, HandlerFailure, type CurrentUser, type HandlerServices, isRecord, numberValue, queryRecord, stringValue, validateWorkflow } from "./common.js";

export const ANALYTICS_UNHANDLED = Symbol("analytics-unhandled");

export async function handleAnalyticsCatalogRoute(route: RouteDefinition, request: FastifyRequest, reply: FastifyReply, user: CurrentUser, services: HandlerServices): Promise<unknown | typeof ANALYTICS_UNHANDLED> {
  const base = services.config.apiBasePath;
  try {
    if (route.path.startsWith(`${base}/analytics/`)) return analytics(route.path.slice(`${base}/analytics/`.length), request, reply, services);
    if (route.path === `${base}/dashboard/summary`) return dashboardSummary(request, reply, services);
    if (route.path === `${base}/dashboard/activity`) return dashboardActivity(reply, services);
    if (route.path === `${base}/dashboard/health`) return dashboardHealth(reply, services);
    if (route.path === `${base}/dashboard/recent-workflows`) return recentWorkflows(request, reply, services);
    if (route.path === `${base}/tools/catalog`) return toolsCatalog(request, reply, services);
    if (route.path === `${base}/rules/catalog`) return rulesCatalog(request, reply, services);
    if (route.path === `${base}/semantic-search`) throw new HandlerFailure(503, "semantic search is not configured");
    if (route.path === `${base}/semantic-index/health` || route.path === `${base}/semantic-index/metadata`) throw new HandlerFailure(503, "semantic search service is not configured");
    if (route.path === `${base}/semantic-index/rebuild`) throw new HandlerFailure(503, "semantic search service is not configured");
    if (route.path === `${base}/synthesis/validate`) return synthesisValidate(request, reply, user, services);
    if (route.path === `${base}/synthesis/preview-flow`) return synthesisPreview(request, reply, services);
    if (route.path === `${base}/synthesis/explain`) return synthesisExplain(request, reply, services);
    if (route.path === `${base}/synthesis`) return synthesis(request, reply, user, services);
    if (route.path === `${base}/canvas/validate-workflow`) return canvasValidate(request, reply, user, services);
  } catch (error) {
    if (error instanceof HandlerFailure) return reply.status(error.status).send(fail(error.message, error.meta));
    throw error;
  }
  return ANALYTICS_UNHANDLED;
}

async function analytics(kind: string, request: FastifyRequest, reply: FastifyReply, services: HandlerServices): Promise<unknown> {
  const executions = await services.repository.read((state) => Object.values(state.executions));
  if (kind === "summary") {
    const today = utcDate(new Date()); const todayRuns = executions.filter((item) => item.startedAt.slice(0, 10) === today); const done = executions.filter((item) => item.status === "DONE").length; const terminal = executions.filter((item) => item.status === "DONE" || item.status === "FAILED").length;
    const data = { runsToday: todayRuns.length, avgLatencyMs: average(executions.map((item) => item.durationMs)), tokenCostUsd: sum(executions.map((item) => item.costUsd)), projectedMonthlyCostUsd: 0, successRate: terminal === 0 ? 0 : round(done * 100 / terminal), healingSuccessRate: 0, validationF1Score: null, validationMetricsAvailable: false };
    return reply.send(ok(data, "OK", { range: stringValue(queryRecord(request).range).trim() === "" ? "7d" : stringValue(queryRecord(request).range) }));
  }
  if (kind === "performance") return reply.send(ok(daySeries(7).map((day) => { const values = executions.filter((item) => item.startedAt.slice(0, 10) === day); const terminal = values.filter((item) => item.status === "DONE" || item.status === "FAILED"); return { label: day, runs: values.length, successRate: terminal.length === 0 ? 0 : round(terminal.filter((item) => item.status === "DONE").length * 100 / terminal.length), avgLatencyMs: average(values.map((item) => item.durationMs)), p95LatencyMs: percentile(values.map((item) => item.durationMs), 0.95) }; }), "OK", { interval: "day" }));
  if (kind === "usage") return reply.send(ok(daySeries(7).map((day) => { const values = executions.filter((item) => item.startedAt.slice(0, 10) === day); return { label: day, inputTokens: sum(values.map((item) => item.tokens.input)), outputTokens: sum(values.map((item) => item.tokens.output)), totalTokens: sum(values.map((item) => item.tokens.total)), costUsd: sum(values.map((item) => item.costUsd)) }; }), "OK", { currency: "USD" }));
  if (kind === "self-healing") { const reports = await services.repository.read((state) => Object.values(state.healing)); const recovered = reports.filter((item) => item.status === "VALIDATED_REPAIR_AVAILABLE").length; return reply.send(ok({ successRate: reports.length === 0 ? 0 : round(recovered * 100 / reports.length), attempts: reports.length, recovered, failed: reports.length - recovered, byReason: [] }, "OK", null)); }
  if (kind === "latency") { const buckets = [{ bucket: "0-500ms", min: 0, max: 500 }, { bucket: "500ms-1s", min: 500, max: 1000 }, { bucket: "1s-2s", min: 1000, max: 2000 }, { bucket: "2s-5s", min: 2000, max: 5000 }, { bucket: "5s+", min: 5000, max: Number.POSITIVE_INFINITY }]; return reply.send(ok(buckets.map(({ bucket, min, max }) => ({ bucket, count: executions.filter((item) => item.durationMs >= min && item.durationMs < max).length })), "OK", null)); }
  if (kind === "f1-score") return reply.send(ok({ available: false, score: null, precision: null, recall: null, samples: 0, falsePositives: 0, falseNegatives: 0 }, "No runtime validation benchmark has been recorded", null));
  if (kind === "activity-heatmap") return reply.send(ok(daySeries(14).map((date) => { const count = executions.filter((item) => item.startedAt.slice(0, 10) === date).length; return { date, count, intensity: Math.min(4, count) }; }), "OK", { timezone: "UTC" }));
  if (kind === "cost-trends") return reply.send(ok(daySeries(7).map((label) => ({ label, costUsd: sum(executions.filter((item) => item.startedAt.slice(0, 10) === label).map((item) => item.costUsd)) })), "OK", { interval: "day" }));
  throw new HandlerFailure(404, "Resource not found");
}

async function dashboardSummary(request: FastifyRequest, reply: FastifyReply, services: HandlerServices): Promise<unknown> { const state = await services.repository.snapshot(); const workflows = Object.values(state.workflows).filter((item) => !item.archived); const executions = Object.values(state.executions); const terminal = executions.filter((item) => item.status === "DONE" || item.status === "FAILED"); const successRate = terminal.length === 0 ? 0 : round(terminal.filter((item) => item.status === "DONE").length * 100 / terminal.length); const metrics = [{ key: "workflows", label: "Workflows", value: workflows.length, formattedValue: String(workflows.length), delta: "", trend: "neutral", icon: "workflow", tone: "blue" }, { key: "executions", label: "Executions", value: executions.length, formattedValue: String(executions.length), delta: "", trend: "neutral", icon: "play", tone: "purple" }, { key: "successRate", label: "Success rate", value: successRate, formattedValue: `${successRate}%`, delta: "", trend: "neutral", icon: "check", tone: "green" }, { key: "cost", label: "Cost", value: sum(executions.map((item) => item.costUsd)), formattedValue: `$${sum(executions.map((item) => item.costUsd)).toFixed(2)}`, delta: "", trend: "neutral", icon: "dollar", tone: "amber" }]; const query = queryRecord(request); return reply.send(ok({ metrics }, "OK", { range: stringValue(query.range).trim() === "" ? "7d" : stringValue(query.range), timezone: stringValue(query.timezone).trim() === "" ? "UTC" : stringValue(query.timezone) })); }
async function dashboardActivity(reply: FastifyReply, services: HandlerServices): Promise<unknown> { const state = await services.repository.snapshot(); const audit = state.auditLogs.filter(isRecord).map((item) => ({ id: item.id, type: "audit", title: item.action, timestamp: item.createdAt, data: item })); const executions = Object.values(state.executions).map((item) => ({ id: item.id, type: "execution", title: `${item.workflowName} ${item.status.toLowerCase()}`, timestamp: item.startedAt, data: item })); const items = [...audit, ...executions].sort((a, b) => stringValue(b.timestamp).localeCompare(stringValue(a.timestamp))).slice(0, 20); return reply.send(ok(items, "OK", { nextCursor: null })); }
async function dashboardHealth(reply: FastifyReply, services: HandlerServices): Promise<unknown> { const storage = await services.repository.persistenceStatus(); const checked = new Date().toISOString(); const servicesList = [{ name: "API", status: "healthy", value: "Operational", meta: {}, lastCheckedAt: checked }, { name: "Storage", status: storage.healthy ? "healthy" : "unhealthy", value: storage.durable ? "Durable" : "Memory", meta: { durable: storage.durable }, lastCheckedAt: checked }, { name: "MCP", status: services.config.mcpBaseURL === "" && services.config.mcpMode === "remote" ? "degraded" : "healthy", value: services.config.mcpMode, meta: {}, lastCheckedAt: checked }]; return reply.send(ok({ overall: servicesList.every((item) => item.status === "healthy") ? "healthy" : "degraded", services: servicesList }, "OK", null)); }
async function recentWorkflows(request: FastifyRequest, reply: FastifyReply, services: HandlerServices): Promise<unknown> { const limit = numberValue(queryRecord(request).limit, 5); const workflows = await services.repository.read((state) => Object.values(state.workflows).filter((item) => !item.archived).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, limit <= 0 ? undefined : limit).map(({ yaml: _yaml, archived: _archived, canvas: _canvas, ...item }) => item)); return reply.send(ok(workflows, "OK", null)); }

async function toolsCatalog(request: FastifyRequest, reply: FastifyReply, services: HandlerServices): Promise<unknown> { const query = queryRecord(request); const moduleName = stringValue(query.module).toLowerCase(); const role = stringValue(query.role).toLowerCase(); const status = stringValue(query.status).toLowerCase(); const tools = services.registries.snapshot().tools.filter((tool) => (moduleName === "" || tool.module.toLowerCase() === moduleName) && (status === "" || tool.status.toLowerCase() === status) && (role === "" || tool.allowed_roles.length === 0 || tool.allowed_roles.some((item) => item.toLowerCase() === role))).map((tool) => ({ tool_id: tool.tool_id, name: tool.name, display_name: tool.display_name, module: tool.module, status: tool.status, risk_level: tool.risk_level, description: tool.description, allowed_roles: tool.allowed_roles, required_parameters: tool.required_parameters, optional_parameters: tool.optional_parameters, is_read_only: tool.is_read_only })); return reply.send(ok(tools, "Tool catalog loaded", { count: tools.length })); }
async function rulesCatalog(request: FastifyRequest, reply: FastifyReply, services: HandlerServices): Promise<unknown> { const query = queryRecord(request); const domain = stringValue(query.domain).toLowerCase(); const enabled = stringValue(query.enabled).toLowerCase(); const rules = services.registries.snapshot().rules.filter((rule) => (domain === "" || rule.domain.toLowerCase() === domain) && (enabled === "" || String(rule.enabled) === enabled)).map((rule) => ({ rule_id: rule.rule_id, rule_name: rule.rule_name, rule_type: rule.rule_type, domain: rule.domain, enabled: rule.enabled, severity: rule.severity, description: rule.description })); return reply.send(ok(rules, "Rule catalog loaded", { count: rules.length })); }
async function semanticSearch(request: FastifyRequest, reply: FastifyReply, user: CurrentUser, services: HandlerServices): Promise<unknown> { const body = bodyRecord(request); if (body === null) throw new HandlerFailure(400, "Invalid request body"); const query = stringValue(body.query).trim(); if (query === "") throw new HandlerFailure(400, "Search query is required"); const topK = Math.max(1, Math.trunc(numberValue(body.top_k, 10))); const tokens = new Set(query.toLowerCase().split(/[^a-z0-9_]+/).filter((item) => item !== "")); const score = (text: string) => { const words = text.toLowerCase().split(/[^a-z0-9_]+/); return words.reduce((total, word) => total + (tokens.has(word) ? 1 : 0), 0); }; const tools = services.registries.snapshot().tools.map((tool) => ({ ...tool, score: score([tool.name, tool.display_name, tool.description, ...tool.semantic_search_keywords].join(" ")), match_reason: "go_lexical equivalent token overlap" })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score || a.name.localeCompare(b.name)).slice(0, topK); const rules = services.registries.snapshot().rules.map((rule) => ({ ...rule, score: score([rule.rule_id, rule.rule_name, rule.description, rule.domain].join(" ")), match_reason: "go_lexical equivalent token overlap" })).filter((item) => item.score > 0).sort((a, b) => b.score - a.score || a.rule_id.localeCompare(b.rule_id)).slice(0, topK); const globalRules = services.registries.snapshot().rules.filter((rule) => rule.enabled && (rule.domain.toLowerCase() === "global" || rule.rule_id.startsWith("GLOBAL-"))); return reply.send(ok({ tools, rules, global_rules: globalRules, templates: [], examples: [], query, user_role: user.role, method: "go_lexical", retrieval_method: "go_lexical" }, "OK", null)); }

async function synthesis(request: FastifyRequest, reply: FastifyReply, user: CurrentUser, services: HandlerServices): Promise<unknown> { const body = bodyRecord(request); if (body === null || stringValue(body.prompt).trim() === "") throw new HandlerFailure(400, "prompt is required"); if (services.synthesis === undefined) throw new HandlerFailure(502, "Workflow synthesis service is not configured"); try { const result = await services.synthesis.synthesize({ prompt: stringValue(body.prompt), userRole: user.role, user: { id: user.id, role: user.role, department: user.departmentId }, model: stringValue(body.model), signal: request.signal }); const meta = result.canExecute ? null : { failed_rules: result.validation.failed_rules, errors: result.validation.errors }; return reply.send(ok(result, result.canExecute ? "Workflow candidate generated and validated" : "Workflow candidate rejected by validation", meta)); } catch (error) { throw new HandlerFailure(502, errorText(error)); } }
async function synthesisValidate(request: FastifyRequest, reply: FastifyReply, user: CurrentUser, services: HandlerServices): Promise<unknown> { const body = bodyRecord(request) ?? {}; const gate = await validateWorkflow(services, "SynthesisValidate", stringValue(body.yaml), user); return reply.send(ok(gate.result, gate.result.passed ? "Workflow is valid" : "Workflow is invalid", null)); }
async function synthesisPreview(request: FastifyRequest, reply: FastifyReply, services: HandlerServices): Promise<unknown> { const body = bodyRecord(request) ?? {}; let blueprint; try { blueprint = parseWorkflowYAMLStrict(stringValue(body.yaml)); } catch (error) { throw new HandlerFailure(422, "Cannot preview invalid YAML", { error: errorText(error) }); } return reply.send(ok(canvasFromBlueprint("preview", blueprint), "Flow preview generated", null)); }
async function synthesisExplain(request: FastifyRequest, reply: FastifyReply, services: HandlerServices): Promise<unknown> { const body = bodyRecord(request) ?? {}; let blueprint; try { blueprint = parseWorkflowYAMLStrict(stringValue(body.yaml)); } catch (error) { throw new HandlerFailure(422, "Cannot explain invalid YAML", { error: errorText(error) }); } return reply.send(ok({ summary: blueprint.description ?? blueprint.name, steps: blueprint.steps.map((step) => ({ id: step.id, action: step.kind === "analysis" ? "analysis" : step.action ?? "", purpose: step.description ?? step.instruction ?? "" })) }, "Workflow explanation generated", null)); }
async function canvasValidate(request: FastifyRequest, reply: FastifyReply, user: CurrentUser, services: HandlerServices): Promise<unknown> { const body = bodyRecord(request); if (body === null) throw new HandlerFailure(400, "Invalid request body"); const yaml = stringValue(body.yaml); if (yaml.trim() === "") throw new HandlerFailure(422, "Canvas node/edge to YAML conversion is not implemented yet. Provide yaml for validation.", { code: "YAML_REQUIRED", suggested_fix: "Provide a non-empty yaml field" }); const gate = await validateWorkflow(services, "CanvasValidateWorkflow", yaml, user); const stepErrors = gate.result.errors.map((message) => ({ message })); return reply.send(ok({ validation: gate.result, step_errors: stepErrors }, gate.result.passed ? "Workflow is valid" : "Workflow is invalid", null)); }

function canvasFromBlueprint(id: string, blueprint: ReturnType<typeof parseWorkflowYAMLStrict>): Record<string, unknown> { const nodes = blueprint.steps.map((step, index) => ({ id: step.id, label: step.description ?? step.action ?? step.id, type: step.kind === undefined || step.kind === "" ? "tool" : step.kind, position: { x: 80 + index * 260, y: 120 }, status: "idle", config: { action: step.action ?? "", parameters: step.parameters ?? {} } })); return { workflowId: id, nodes, edges: nodes.slice(1).map((node, index) => ({ id: `edge_${index + 1}`, source: nodes[index]!.id, target: node.id, type: "default", label: null })), viewport: { x: 0, y: 0, zoom: 1 } }; }
function daySeries(count: number): string[] { const values: string[] = []; const current = new Date(); current.setUTCHours(0, 0, 0, 0); for (let offset = count - 1; offset >= 0; offset -= 1) { const date = new Date(current); date.setUTCDate(current.getUTCDate() - offset); values.push(utcDate(date)); } return values; }
function utcDate(date: Date): string { return date.toISOString().slice(0, 10); }
function sum(values: number[]): number { return values.reduce((total, value) => total + value, 0); }
function average(values: number[]): number { return values.length === 0 ? 0 : Math.trunc(sum(values) / values.length); }
function round(value: number): number { return Math.round(value * 100) / 100; }
function percentile(values: number[], p: number): number { if (values.length === 0) return 0; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.max(0, Math.ceil(sorted.length * p) - 1)] ?? 0; }
function errorText(error: unknown): string { return error instanceof Error ? error.message : String(error); }
