export const PERMISSIONS = {
  WORKFLOW_READ: "workflow:read",
  WORKFLOW_WRITE: "workflow:write",
  WORKFLOW_RUN: "workflow:run",
  WORKFLOW_VIEW_ALL: "workflow_view_all",
  CHAT_USE: "chat:use",
  WORKFLOW_READ_OWN: "workflow:read_own",
  WORKFLOW_RUN_OWN: "workflow:run_own",
  EXECUTION_READ_OWN: "execution:read_own",
  USER_MANAGE: "user:manage",
  SETTINGS_MANAGE: "settings:manage",
  PROVIDER_MANAGE: "provider:manage",
  REGISTRY_READ: "registry:read",
  REGISTRY_WRITE: "registry:write",
  AUDIT_READ: "audit:read",
};
