package routes

import (
	"github.com/gofiber/contrib/websocket"
	"github.com/gofiber/fiber/v2"
	"github.com/sanjeewa/agentic-orchestrator/internal/api/handlers"
	"github.com/sanjeewa/agentic-orchestrator/internal/api/middlewares"
)

func Register(app *fiber.App, h *handlers.Handler) {
	app.Get("/healthz", h.Health)
	app.Get("/ws/*", middlewares.Auth(h.Cfg.JWTSecret, false), h.RequireUser, websocket.New(h.WebSocketEvents))

	api := app.Group(h.Cfg.APIBasePath)
	api.Get("/health", h.Health)

	auth := api.Group("/auth")
	auth.Post("/login", h.Login)
	auth.Post("/register", h.Register)
	auth.Post("/refresh", h.Refresh)
	auth.Post("/forgot-password", h.ForgotPassword)
	auth.Post("/reset-password", h.ResetPassword)
	auth.Post("/verify-email", h.VerifyEmail)
	auth.Get("/oauth/:provider/authorize", h.OAuthAuthorize)
	auth.Get("/oauth/:provider/callback", h.OAuthCallback)

	protected := api.Group("", middlewares.Auth(h.Cfg.JWTSecret, h.Cfg.AllowDevAuth), h.RequireUser)
	workflowRead := middlewares.RequirePermission("workflow:read", h.Permissions)
	workflowWrite := middlewares.RequirePermission("workflow:write", h.Permissions)
	workflowRun := middlewares.RequirePermission("workflow:run", h.Permissions)
	settingsManage := middlewares.RequirePermission("settings:manage", h.Permissions)
	userManage := middlewares.RequirePermission("user:manage", h.Permissions)
	auditRead := middlewares.RequirePermission("audit:read", h.Permissions)

	protected.Post("/auth/logout", h.Logout)
	protected.Get("/auth/me", h.Me)
	protected.Post("/auth/2fa/verify", h.TwoFactorVerify)
	protected.Post("/auth/2fa/enable", h.TwoFactorEnable)
	protected.Post("/auth/2fa/disable", h.TwoFactorDisable)

	protected.Get("/dashboard/summary", workflowRead, h.DashboardSummary)
	protected.Get("/dashboard/activity", workflowRead, h.DashboardActivity)
	protected.Get("/dashboard/health", workflowRead, h.DashboardHealth)
	protected.Get("/dashboard/recent-workflows", workflowRead, h.RecentWorkflows)

	protected.Get("/workflows/templates", workflowRead, h.ListTemplates)
	protected.Post("/workflows/templates", workflowWrite, h.CreateTemplate)
	protected.Post("/workflows/templates/:id/use", workflowWrite, h.UseTemplate)
	protected.Get("/workflows", workflowRead, h.ListWorkflows)
	protected.Post("/workflows", workflowWrite, h.CreateWorkflow)
	protected.Get("/workflows/:id", workflowRead, h.GetWorkflow)
	protected.Patch("/workflows/:id", workflowWrite, h.UpdateWorkflow)
	protected.Delete("/workflows/:id", workflowWrite, h.DeleteWorkflow)
	protected.Post("/workflows/:id/duplicate", workflowWrite, h.DuplicateWorkflow)
	protected.Post("/workflows/:id/publish", workflowWrite, h.PublishWorkflow)
	protected.Post("/workflows/:id/archive", workflowWrite, h.ArchiveWorkflow)
	protected.Post("/workflows/:id/validate", workflowRead, h.ValidateWorkflow)
	protected.Post("/workflows/:id/run", workflowRun, h.RunWorkflow)
	protected.Get("/workflows/:id/yaml", workflowRead, h.GetWorkflowYAML)
	protected.Put("/workflows/:id/yaml", workflowWrite, h.PutWorkflowYAML)
	protected.Get("/workflows/:id/canvas", workflowRead, h.GetWorkflowCanvas)
	protected.Put("/workflows/:id/canvas", workflowWrite, h.PutWorkflowCanvas)
	protected.Get("/workflows/:id/versions", workflowRead, h.WorkflowVersions)
	protected.Post("/workflows/:id/restore/:versionId", workflowWrite, h.RestoreWorkflowVersion)
	protected.Get("/workflows/:id/executions", workflowRead, h.WorkflowExecutions)

	protected.Post("/synthesis", workflowWrite, h.Synthesize)
	protected.Post("/synthesis/validate", workflowRead, h.SynthesisValidate)
	protected.Post("/synthesis/preview-flow", workflowRead, h.SynthesisPreviewFlow)
	protected.Post("/synthesis/explain", workflowRead, h.SynthesisExplain)
	protected.Get("/tools/catalog", workflowRead, h.ToolsCatalog)
	protected.Get("/rules/catalog", workflowRead, h.RulesCatalog)
	protected.Post("/semantic-search", workflowRead, h.SemanticSearch)
	protected.Get("/semantic-index/health", workflowRead, h.SemanticServiceHealth)
	protected.Get("/semantic-index/metadata", workflowRead, h.SemanticIndexMetadata)
	protected.Post("/semantic-index/rebuild", settingsManage, h.RebuildSemanticIndex)
	protected.Post("/canvas/validate-workflow", workflowRead, h.CanvasValidateWorkflow)
	protected.Get("/registry/tools", settingsManage, h.AdminToolsRegistry)
	protected.Post("/registry/tools", settingsManage, h.CreateRegistryTool)
	protected.Put("/registry/tools/:id", settingsManage, h.UpdateRegistryTool)
	protected.Get("/registry/rules", settingsManage, h.AdminRulesRegistry)
	protected.Post("/registry/rules", settingsManage, h.CreateRegistryRule)
	protected.Put("/registry/rules/:id", settingsManage, h.UpdateRegistryRule)

	protected.Get("/chat/sessions", workflowRead, h.ListChatSessions)
	protected.Post("/chat/sessions", workflowWrite, h.CreateChatSession)
	protected.Get("/chat/sessions/:id", workflowRead, h.GetChatSession)
	protected.Patch("/chat/sessions/:id", workflowWrite, h.UpdateChatSession)
	protected.Delete("/chat/sessions/:id", workflowWrite, h.DeleteChatSession)
	protected.Post("/chat/sessions/:id/messages", workflowWrite, h.SendChatMessage)

	protected.Get("/executions", workflowRead, h.ListExecutions)
	protected.Get("/executions/:id", workflowRead, h.GetExecution)
	protected.Get("/executions/:id/logs", workflowRead, h.ExecutionLogs)
	protected.Get("/executions/:id/timeline", workflowRead, h.ExecutionTimeline)
	protected.Get("/executions/:id/healing-report", workflowRead, h.ExecutionHealingReport)
	protected.Post("/executions/:id/cancel", workflowRun, h.CancelExecution)
	protected.Post("/executions/:id/retry", workflowRun, h.RetryExecution)

	protected.Get("/analytics/summary", workflowRead, h.AnalyticsSummary)
	protected.Get("/analytics/performance", workflowRead, h.AnalyticsPerformance)
	protected.Get("/analytics/usage", workflowRead, h.AnalyticsUsage)
	protected.Get("/analytics/self-healing", workflowRead, h.AnalyticsSelfHealing)
	protected.Get("/analytics/latency", workflowRead, h.AnalyticsLatency)
	protected.Get("/analytics/f1-score", workflowRead, h.AnalyticsF1Score)
	protected.Get("/analytics/activity-heatmap", workflowRead, h.AnalyticsActivityHeatmap)
	protected.Get("/analytics/cost-trends", workflowRead, h.AnalyticsCostTrends)

	protected.Get("/users", userManage, h.ListUsers)
	protected.Post("/users", userManage, h.CreateUser)
	protected.Post("/users/invite", userManage, h.InviteUser)
	protected.Get("/users/:id", userManage, h.GetUser)
	protected.Patch("/users/:id", userManage, h.UpdateUser)
	protected.Delete("/users/:id", userManage, h.DeleteUser)
	protected.Post("/users/:id/activate", userManage, h.ActivateUser)
	protected.Post("/users/:id/suspend", userManage, h.SuspendUser)
	protected.Get("/roles", userManage, h.ListRoles)
	protected.Post("/roles", userManage, h.CreateRole)
	protected.Get("/roles/:id", userManage, h.GetRole)
	protected.Patch("/roles/:id", userManage, h.UpdateRole)
	protected.Delete("/roles/:id", userManage, h.DeleteRole)
	protected.Get("/permissions", userManage, h.ListPermissions)
	protected.Get("/permissions/matrix", userManage, h.PermissionMatrix)
	protected.Get("/audit/export", auditRead, h.ExportAudit)
	protected.Get("/audit", auditRead, h.ListAudit)
	protected.Get("/audit/:id", auditRead, h.GetAudit)

	protected.Get("/profile", h.GetProfile)
	protected.Patch("/profile", h.UpdateProfile)
	protected.Patch("/profile/security", h.UpdateSecurity)
	protected.Get("/profile/notifications", h.GetNotificationPreferences)
	protected.Patch("/profile/notifications", h.UpdateNotificationPreferences)
	protected.Get("/profile/api-keys", settingsManage, h.ListAPIKeys)
	protected.Post("/profile/api-keys", settingsManage, h.CreateAPIKey)
	protected.Delete("/profile/api-keys/:id", settingsManage, h.DeleteAPIKey)

	protected.Get("/settings", settingsManage, h.GetSettings)
	protected.Patch("/settings", settingsManage, h.PatchSettings)
	protected.Get("/settings/general", settingsManage, h.GetGeneralSettings)
	protected.Patch("/settings/general", settingsManage, h.PatchGeneralSettings)
	protected.Get("/settings/llm", settingsManage, h.GetLLMSettings)
	protected.Patch("/settings/llm", settingsManage, h.PatchLLMSettings)
	protected.Get("/providers", settingsManage, h.ListProviders)
	protected.Post("/providers", settingsManage, h.CreateProvider)
	protected.Put("/providers/:id", settingsManage, h.UpdateProvider)
	protected.Post("/providers/:id/activate", settingsManage, h.ActivateProvider)
	protected.Post("/providers/:id/test", settingsManage, h.TestProvider)
	protected.Get("/settings/rbac", settingsManage, h.GetRBACSettings)
	protected.Patch("/settings/rbac", settingsManage, h.PatchRBACSettings)
	protected.Get("/settings/webhooks", settingsManage, h.ListWebhooks)
	protected.Post("/settings/webhooks", settingsManage, h.CreateWebhook)
	protected.Patch("/settings/webhooks/:id", settingsManage, h.UpdateWebhook)
	protected.Delete("/settings/webhooks/:id", settingsManage, h.DeleteWebhook)
	protected.Post("/settings/webhooks/:id/test", settingsManage, h.TestWebhook)

	protected.Get("/integrations", settingsManage, h.ListIntegrations)
	protected.Post("/integrations", settingsManage, h.CreateIntegration)
	protected.Get("/integrations/:id", settingsManage, h.GetIntegration)
	protected.Patch("/integrations/:id", settingsManage, h.UpdateIntegration)
	protected.Delete("/integrations/:id", settingsManage, h.DeleteIntegration)
	protected.Post("/integrations/:id/test", settingsManage, h.TestIntegration)
	protected.Post("/integrations/:id/connect", settingsManage, h.ConnectIntegration)
	protected.Post("/integrations/:id/disconnect", settingsManage, h.DisconnectIntegration)

	protected.Get("/notifications", h.ListNotifications)
	protected.Patch("/notifications/read-all", h.MarkAllNotificationsRead)
	protected.Patch("/notifications/:id/read", h.MarkNotificationRead)
	protected.Delete("/notifications/:id", h.DeleteNotification)
	protected.Post("/upload", workflowWrite, h.Upload)
	protected.Get("/upload/:id", workflowRead, h.GetUpload)
	protected.Get("/upload/:id/download", workflowRead, h.DownloadUpload)
	protected.Delete("/upload/:id", workflowWrite, h.DeleteUpload)
	protected.Post("/upload/workflow-import", workflowWrite, h.ImportWorkflow)
}
