package routes

import (
	"time"

	"github.com/gofiber/contrib/websocket"
	"github.com/gofiber/fiber/v2"
	"github.com/sanjeewa/agentic-orchestrator/internal/api/handlers"
	"github.com/sanjeewa/agentic-orchestrator/internal/api/middlewares"
)

func Register(app *fiber.App, h *handlers.Handler) {
	app.Get("/healthz", h.Health)
	app.Get("/ws/*", middlewares.Auth(h.Cfg.JWTSecret), h.RequireUser, websocket.New(h.WebSocketEvents))

	api := app.Group(h.Cfg.APIBasePath)
	api.Get("/health", h.Health)

	auth := api.Group("/auth")
	authMutationLimiter := middlewares.RateLimit(10, time.Minute)
	auth.Post("/login", authMutationLimiter, h.Login)
	auth.Post("/register", authMutationLimiter, h.Register)
	auth.Post("/refresh", authMutationLimiter, h.Refresh)
	auth.Post("/forgot-password", authMutationLimiter, h.ForgotPassword)
	auth.Post("/reset-password", authMutationLimiter, h.ResetPassword)
	auth.Post("/verify-email", authMutationLimiter, h.VerifyEmail)
	auth.Get("/oauth/:provider/authorize", h.OAuthAuthorize)
	auth.Get("/oauth/:provider/callback", h.OAuthCallback)

	protected := api.Group("", middlewares.Auth(h.Cfg.JWTSecret), h.RequireUser)
	workflowRead := middlewares.RequirePermission("workflow:read", h.Permissions)
	workflowWrite := middlewares.RequirePermission("workflow:write", h.Permissions)
	workflowRun := middlewares.RequirePermission("workflow:run", h.Permissions)
	workflowReadAny := middlewares.RequireAnyPermission([]string{"workflow:read", "workflow:read_own"}, h.Permissions)
	workflowRunAny := middlewares.RequireAnyPermission([]string{"workflow:run", "workflow:run_own"}, h.Permissions)
	executionReadAny := middlewares.RequireAnyPermission([]string{"workflow:read", "execution:read_own"}, h.Permissions)
	chatReadAny := middlewares.RequireAnyPermission([]string{"workflow:read", "chat:use"}, h.Permissions)
	chatWriteAny := middlewares.RequireAnyPermission([]string{"workflow:write", "chat:use"}, h.Permissions)
	settingsManage := middlewares.RequirePermission("settings:manage", h.Permissions)
	providerManage := middlewares.RequirePermission("provider:manage", h.Permissions)
	registryRead := middlewares.RequirePermission("registry:read", h.Permissions)
	registryWrite := middlewares.RequirePermission("registry:write", h.Permissions)
	userManage := middlewares.RequirePermission("user:manage", h.Permissions)
	auditRead := middlewares.RequirePermission("audit:read", h.Permissions)

	protected.Post("/auth/logout", h.Logout)
	protected.Get("/auth/me", h.Me)
	protected.Post("/auth/2fa/verify", h.TwoFactorVerify)
	protected.Post("/auth/2fa/enable", h.TwoFactorEnable)
	protected.Post("/auth/2fa/disable", h.TwoFactorDisable)

	protected.Get("/company", h.GetCompany)
	protected.Put("/company", h.UpdateCompany)
	protected.Get("/company/departments", h.ListCompanyDepartments)
	protected.Post("/company/departments", h.CreateCompanyDepartment)
	protected.Put("/company/departments/:id", h.UpdateCompanyDepartment)
	protected.Delete("/company/departments/:id", h.DeleteCompanyDepartment)
	protected.Get("/company/cost-centres", h.ListCompanyCostCentres)
	protected.Post("/company/cost-centres", h.CreateCompanyCostCentre)
	protected.Put("/company/cost-centres/:id", h.UpdateCompanyCostCentre)
	protected.Delete("/company/cost-centres/:id", h.DeleteCompanyCostCentre)
	protected.Get("/company/approval-tiers", h.ListCompanyApprovalTiers)
	protected.Post("/company/approval-tiers", h.CreateCompanyApprovalTier)
	protected.Put("/company/approval-tiers/:id", h.UpdateCompanyApprovalTier)
	protected.Delete("/company/approval-tiers/:id", h.DeleteCompanyApprovalTier)

	protected.Get("/dashboard/summary", workflowRead, h.DashboardSummary)
	protected.Get("/dashboard/activity", workflowRead, h.DashboardActivity)
	protected.Get("/dashboard/health", workflowRead, h.DashboardHealth)
	protected.Get("/dashboard/recent-workflows", workflowRead, h.RecentWorkflows)

	protected.Get("/workflows/templates", workflowRead, h.ListTemplates)
	protected.Post("/workflows/templates", workflowWrite, h.CreateTemplate)
	protected.Post("/workflows/templates/:id/use", workflowWrite, h.UseTemplate)
	protected.Get("/workflows", workflowReadAny, h.ListWorkflows)
	protected.Post("/workflows", workflowWrite, h.CreateWorkflow)
	protected.Get("/workflows/assignable-users", workflowWrite, h.ListAssignableWorkflowUsers)
	protected.Get("/workflows/:id", workflowReadAny, h.GetWorkflow)
	protected.Patch("/workflows/:id", workflowWrite, h.UpdateWorkflow)
	protected.Delete("/workflows/:id", workflowWrite, h.DeleteWorkflow)
	protected.Post("/workflows/:id/duplicate", workflowWrite, h.DuplicateWorkflow)
	protected.Post("/workflows/:id/publish", workflowWrite, h.PublishWorkflow)
	protected.Post("/workflows/:id/archive", workflowWrite, h.ArchiveWorkflow)
	protected.Post("/workflows/:id/validate", workflowRead, h.ValidateWorkflow)
	protected.Post("/workflows/:id/run", workflowRunAny, h.RunWorkflow)
	protected.Post("/workflows/:id/assign", workflowWrite, h.AssignWorkflowUser)
	protected.Delete("/workflows/:id/assign/:userId", workflowWrite, h.UnassignWorkflowUser)
	protected.Get("/workflows/:id/yaml", workflowReadAny, h.GetWorkflowYAML)
	protected.Put("/workflows/:id/yaml", workflowWrite, h.PutWorkflowYAML)
	protected.Get("/workflows/:id/canvas", workflowReadAny, h.GetWorkflowCanvas)
	protected.Put("/workflows/:id/canvas", workflowWrite, h.PutWorkflowCanvas)
	protected.Get("/workflows/:id/versions", workflowReadAny, h.WorkflowVersions)
	protected.Post("/workflows/:id/restore/:versionId", workflowWrite, h.RestoreWorkflowVersion)
	protected.Get("/workflows/:id/executions", workflowReadAny, h.WorkflowExecutions)

	protected.Post("/synthesis", workflowWrite, h.Synthesize)
	protected.Post("/synthesis/validate", workflowRead, h.SynthesisValidate)
	protected.Post("/synthesis/preview-flow", workflowRead, h.SynthesisPreviewFlow)
	protected.Post("/synthesis/explain", workflowRead, h.SynthesisExplain)
	protected.Get("/tools/catalog", workflowRead, h.ToolsCatalog)
	protected.Get("/rules/catalog", workflowRead, h.RulesCatalog)
	protected.Post("/semantic-search", workflowRead, h.SemanticSearch)
	protected.Get("/semantic-index/health", workflowRead, h.SemanticServiceHealth)
	protected.Get("/semantic-index/metadata", workflowRead, h.SemanticIndexMetadata)
	protected.Post("/semantic-index/rebuild", settingsManage, h.RebuildSemanticIndex)
	protected.Post("/canvas/validate-workflow", workflowRead, h.CanvasValidateWorkflow)
	protected.Get("/registry/tools", registryRead, h.AdminToolsRegistry)
	protected.Get("/registry/status", registryRead, h.RegistryStatus)
	protected.Get("/registry/context", registryRead, h.GetRegistryContext)
	protected.Post("/registry/context/regenerate", registryWrite, h.RegenerateRegistryContext)
	protected.Get("/registry/context/history", registryRead, h.RegistryContextHistory)
	protected.Post("/registry/tools/import", settingsManage, h.ImportRegistryTools)
	protected.Post("/registry/tools", registryWrite, h.CreateRegistryTool)
	protected.Put("/registry/tools/:id", registryWrite, h.UpdateRegistryTool)
	protected.Get("/registry/rules", registryRead, h.AdminRulesRegistry)
	protected.Post("/registry/rules/import", settingsManage, h.ImportRegistryRules)
	protected.Post("/registry/rules", registryWrite, h.CreateRegistryRule)
	protected.Put("/registry/rules/:id", registryWrite, h.UpdateRegistryRule)
	protected.Post("/import/analyse", registryWrite, h.AnalyseRegistryImport)
	protected.Post("/import/commit", registryWrite, h.CommitRegistryImport)
	protected.Get("/import/history", registryWrite, h.RegistryImportHistory)

	protected.Get("/chat/sessions", chatReadAny, h.ListChatSessions)
	protected.Post("/chat/sessions", chatWriteAny, h.CreateChatSession)
	protected.Get("/chat/sessions/:id", chatReadAny, h.GetChatSession)
	protected.Patch("/chat/sessions/:id", chatWriteAny, h.UpdateChatSession)
	protected.Delete("/chat/sessions/:id", chatWriteAny, h.DeleteChatSession)
	protected.Post("/chat/sessions/:id/messages", chatWriteAny, h.SendChatMessage)

	protected.Get("/executions", executionReadAny, h.ListExecutions)
	protected.Get("/executions/:id", executionReadAny, h.GetExecution)
	protected.Get("/executions/:id/logs", executionReadAny, h.ExecutionLogs)
	protected.Get("/executions/:id/timeline", executionReadAny, h.ExecutionTimeline)
	protected.Get("/executions/:id/healing-report", executionReadAny, h.ExecutionHealingReport)
	protected.Post("/executions/:id/cancel", workflowRun, h.CancelExecution)
	protected.Post("/executions/:id/retry", workflowRunAny, h.RetryExecution)

	protected.Get("/analytics/summary", workflowRead, h.AnalyticsSummary)
	protected.Get("/analytics/performance", workflowRead, h.AnalyticsPerformance)
	protected.Get("/analytics/usage", workflowRead, h.AnalyticsUsage)
	protected.Get("/analytics/self-healing", workflowRead, h.AnalyticsSelfHealing)
	protected.Get("/analytics/latency", workflowRead, h.AnalyticsLatency)
	protected.Get("/analytics/f1-score", workflowRead, h.AnalyticsF1Score)
	protected.Get("/analytics/activity-heatmap", workflowRead, h.AnalyticsActivityHeatmap)
	protected.Get("/analytics/cost-trends", workflowRead, h.AnalyticsCostTrends)

	protected.Get("/users", userManage, h.ListUsers)
	protected.Post("/users", userManage, h.CreateUser)
	protected.Post("/users/invite", userManage, h.InviteUser)
	protected.Get("/users/:id", userManage, h.GetUser)
	protected.Patch("/users/:id", userManage, h.UpdateUser)
	protected.Put("/users/:id/role", userManage, h.UpdateUserRole)
	protected.Put("/users/:id/status", userManage, h.UpdateUserStatus)
	protected.Delete("/users/:id", userManage, h.DeleteUser)
	protected.Post("/users/:id/activate", userManage, h.ActivateUser)
	protected.Post("/users/:id/suspend", userManage, h.SuspendUser)
	protected.Get("/roles", userManage, h.ListRoles)
	protected.Post("/roles", userManage, h.CreateRole)
	protected.Get("/roles/:id", userManage, h.GetRole)
	protected.Put("/roles/:id", userManage, h.UpdateRole)
	protected.Patch("/roles/:id", userManage, h.UpdateRole)
	protected.Delete("/roles/:id", userManage, h.DeleteRole)
	protected.Get("/permissions", userManage, h.ListPermissions)
	protected.Get("/permissions/matrix", userManage, h.PermissionMatrix)
	protected.Get("/audit/export", auditRead, h.ExportAudit)
	protected.Get("/audit", auditRead, h.ListAudit)
	protected.Get("/audit/:id", auditRead, h.GetAudit)

	protected.Get("/profile", h.GetProfile)
	protected.Patch("/profile", h.UpdateProfile)
	protected.Patch("/profile/security", h.UpdateSecurity)
	protected.Get("/profile/notifications", h.GetNotificationPreferences)
	protected.Patch("/profile/notifications", h.UpdateNotificationPreferences)
	protected.Get("/profile/api-keys", settingsManage, h.ListAPIKeys)
	protected.Post("/profile/api-keys", settingsManage, h.CreateAPIKey)
	protected.Delete("/profile/api-keys/:id", settingsManage, h.DeleteAPIKey)

	protected.Get("/settings", settingsManage, h.GetSettings)
	protected.Patch("/settings", settingsManage, h.PatchSettings)
	protected.Get("/settings/general", settingsManage, h.GetGeneralSettings)
	protected.Patch("/settings/general", settingsManage, h.PatchGeneralSettings)
	protected.Get("/settings/llm", settingsManage, h.GetLLMSettings)
	protected.Patch("/settings/llm", settingsManage, h.PatchLLMSettings)
	protected.Get("/providers", providerManage, h.ListProviders)
	protected.Post("/providers", providerManage, h.CreateProvider)
	protected.Put("/providers/:id", providerManage, h.UpdateProvider)
	protected.Post("/providers/:id/activate", providerManage, h.ActivateProvider)
	protected.Post("/providers/:id/test", providerManage, h.TestProvider)
	protected.Get("/settings/rbac", settingsManage, h.GetRBACSettings)
	protected.Patch("/settings/rbac", settingsManage, h.PatchRBACSettings)
	protected.Get("/settings/webhooks", settingsManage, h.ListWebhooks)
	protected.Post("/settings/webhooks", settingsManage, h.CreateWebhook)
	protected.Patch("/settings/webhooks/:id", settingsManage, h.UpdateWebhook)
	protected.Delete("/settings/webhooks/:id", settingsManage, h.DeleteWebhook)
	protected.Post("/settings/webhooks/:id/test", settingsManage, h.TestWebhook)

	protected.Get("/integrations", settingsManage, h.ListIntegrations)
	protected.Post("/integrations", settingsManage, h.CreateIntegration)
	protected.Get("/integrations/:id", settingsManage, h.GetIntegration)
	protected.Patch("/integrations/:id", settingsManage, h.UpdateIntegration)
	protected.Delete("/integrations/:id", settingsManage, h.DeleteIntegration)
	protected.Post("/integrations/:id/test", settingsManage, h.TestIntegration)
	protected.Post("/integrations/:id/connect", settingsManage, h.ConnectIntegration)
	protected.Post("/integrations/:id/disconnect", settingsManage, h.DisconnectIntegration)

	protected.Get("/notifications", h.ListNotifications)
	protected.Patch("/notifications/read-all", h.MarkAllNotificationsRead)
	protected.Patch("/notifications/:id/read", h.MarkNotificationRead)
	protected.Delete("/notifications/:id", h.DeleteNotification)
	protected.Post("/upload", workflowWrite, h.Upload)
	protected.Get("/upload/:id", workflowRead, h.GetUpload)
	protected.Get("/upload/:id/download", workflowRead, h.DownloadUpload)
	protected.Delete("/upload/:id", workflowWrite, h.DeleteUpload)
	protected.Post("/upload/workflow-import", workflowWrite, h.ImportWorkflow)
}
